on:
  workflow_dispatch:
  pull_request:
    paths:
      - PromiseKit.podspec
jobs:
  lint:
    runs-on: macos-15
    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 16
    - uses: maxim-lobanov/setup-cocoapods@v1
      with:
        version: 1.16.2
    - uses: actions/checkout@v2
      with:
        submodules: true
    - run: pod lib lint --fail-fast --allow-warnings
